create table author (id bigint not null, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
create table author_book (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id)) engine=InnoDB;
create table book (id bigint not null, isbn varchar(255), title varchar(255), publisher_id bigint, primary key (id)) engine=InnoDB;
create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table ingredient (id bigint not null auto_increment, amount decimal(19,2), description varchar(255), recipe_id bigint, uom_id bigint, primary key (id)) engine=InnoDB;
create table note (id bigint not null auto_increment, recipe_note longtext, recipe_id bigint, primary key (id)) engine=InnoDB;
create table publisher (id bigint not null, address varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, cook_time integer, description varchar(255), difficulty varchar(255), directions longtext, image longblob, prep_time integer, servings integer, source varchar(255), url varchar(255), note_id bigint, primary key (id)) engine=InnoDB;
create table recipe_category (recipe_id bigint not null, category_id bigint not null, primary key (recipe_id, category_id)) engine=InnoDB;
create table unit_of_measure (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=InnoDB;
alter table author_book add constraint FKg7j6ud9d32ll232o9mgo90s57 foreign key (author_id) references author (id);
alter table author_book add constraint FKn8665s8lv781v4eojs8jo3jao foreign key (book_id) references book (id);
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher (id);
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table note add constraint FKaeln1ftj8676mm6e78iu7ibwq foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FKlf335hpxlg22j27pg6mk4k9xt foreign key (note_id) references note (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
